project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/sherylanntan
      - icon: github
        href: https://github.com/sherylanntys
    
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Hands-On Exercise 0"
          href: Hands-on Exercise/Hands-on_Ex00/Hands-on_Ex00.html
        - text: "Hands-On Exercise 1"
          href: Hands-on Exercise/Hands-on_Ex01/Hands-on_Ex01.html
        - text: "Hands-On Exercise 2"
          href: Hands-on Exercise/Hands-on_Ex02/Hands-on_Ex02.html
          
      - text: "In-class Exercise"
        menu:
        - text: "In-class Exercise 1"
          href: https://public.tableau.com/app/profile/sherylanntys/viz/In-class_Ex01_17371867514480/Dashboard1
      - text: "Take-home Exercise"
        menu: 
        - text: "Take-home Exercise 1 - Coming Soon"
          href: Take-Home_Ex1.html


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

