project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Hands-On Exercise 0"
          href: Hands-on Exercise/Hands-on_Ex00/Hands-on_Ex00.html
      - text: "In-class Exercise"
        menu:
        - text: "In-class Exercise 1"
          href: In-class_Ex1.html
      - text: "Take-home Exercise"
        menu: 
        - text: "Take-home Exercise 1"
          href: Take-Home_Ex1.html


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

