project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/sherylanntan
      - icon: github
        href: https://github.com/sherylanntys
    
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Hands-On Exercise 0.0"
          href: Hands-on Exercise/Hands-on_Ex00/Hands-on_Ex00.html
        - text: "Hands-On Exercise 1.0"
          href: Hands-on Exercise/Hands-on_Ex01/Hands-on_Ex01.html
        - text: "Hands-On Exercise 2.0"
          href: Hands-on Exercise/Hands-on_Ex02/Hands-on_Ex02.html
        - text: "Hands-On Exercise 3.1"
          href: Hands-on Exercise/Hands-on_Ex03/Hands-on_Ex03.html
        - text: "Hands-On Exercise 3.2"
          href: Hands-on Exercise/Hands-on_Ex03/Hands-on_Ex03b.html
        - text: "Hands-On Exercise 4.1"
          href: Hands-on Exercise/Hands-on_Ex04/Hands-on_Ex041.html
        - text: "Hands-On Exercise 4.2"
          href: Hands-on Exercise/Hands-on_Ex04/Hands-on_Ex042.html
        - text: "Hands-On Exercise 4.3"
          href: Hands-on Exercise/Hands-on_Ex04/Hands-on_Ex043.html
          
      - text: "In-class Exercise"
        menu:
        - text: "In-class Exercise 1.0"
          href: https://public.tableau.com/app/profile/sherylanntys/viz/In-class_Ex01_17377898729330/Dashboard1
        - text: "In-class Exercise 2.0"
          href: https://public.tableau.com/app/profile/sherylanntys/viz/In-class_Ex01_17371867514480/Dashboard2
      - text: "Take-home Exercise"
        menu: 
        - text: "Take-home Exercise 1 - Coming Soon"
          href: Take-Home Exercise/Take-Home_Ex01/Take-Home_Ex01.html


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

