project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/sherylanntan
      - icon: github
        href: https://github.com/sherylanntys
    
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Hands-On Exercise 0.0"
          href: Hands-on Exercise/Hands-on_Ex00/Hands-on_Ex00.html
        - text: "Hands-On Exercise 1.0"
          href: Hands-on Exercise/Hands-on_Ex01/Hands-on_Ex01.html
        - text: "Hands-On Exercise 2.0"
          href: Hands-on Exercise/Hands-on_Ex02/Hands-on_Ex02.html
        - text: "Hands-On Exercise 3.1"
          href: Hands-on Exercise/Hands-on_Ex03/Hands-on_Ex03.html
        - text: "Hands-On Exercise 3.2"
          href: Hands-on Exercise/Hands-on_Ex03/Hands-on_Ex03b.html
        - text: "Hands-On Exercise 4.1"
          href: Hands-on Exercise/Hands-on_Ex04/Hands-on_Ex041.html
        - text: "Hands-On Exercise 4.2"
          href: Hands-on Exercise/Hands-on_Ex04/Hands-on_Ex042.html
        - text: "Hands-On Exercise 4.3"
          href: Hands-on Exercise/Hands-on_Ex04/Hands-on_Ex043.html
        - text: "Hands-On Exercise 4.4"
          href: Hands-on Exercise/Hands-on_Ex04/Hands-on_Ex044.html
        - text: "Hands-On Exercise 5.1"
          href: Hands-on Exercise/Hands-on_Ex05/Hands-on_Ex051.html
        - text: "Hands-On Exercise 5.2"
          href: Hands-on Exercise/Hands-on_Ex05/Hands-on_Ex052.html
        - text: "Hands-On Exercise 5.3"
          href: Hands-on Exercise/Hands-on_Ex05/Hands-on_Ex053.html
        - text: "Hands-On Exercise 5.4"
          href: Hands-on Exercise/Hands-on_Ex05/Hands-on_Ex054.html
        - text: "Hands-On Exercise 5.5"
          href: Hands-on Exercise/Hands-on_Ex05/Hands-on_Ex055.html
        - text: "Hands-On Exercise 7.0"
          href: Hands-on Exercise/Hands-on_Ex07/Hands-on_Ex07.html
          
      - text: "In-class Exercise"
        menu:
        - text: "In-class Exercise 1.0"
          href: https://public.tableau.com/app/profile/sherylanntys/viz/In-class_Ex01_17377898729330/Dashboard1
        - text: "In-class Exercise 2.0"
          href: https://public.tableau.com/app/profile/sherylanntys/viz/In-class_Ex01_17371867514480/Dashboard2
        - text: "In-class Exercise 4.0"
          href: In-class Exercise/In-class_Ex04/In-class_Ex04.html
        - text: "In-class Exercise 5.0"
          href: In-class Exercise/In-class_Ex05/In-class_Ex05.html
      
      
      
      - text: "Take-home Exercise"
        menu: 
        - text: "Take-home Exercise 1.0"
          href: Take-Home Exercise/Take-Home_Ex01/Take-Home_Ex01b.html
        - text: "Take-home Exercise 2.0"
          href: Take-Home Exercise/Take-Home_Ex01/Take-Home_Ex01b.html


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

