{
  "hash": "b7b5b21a5a13513385fc04560c5ce9fa",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-Home Exercise 1.0: Creating Data Visualisation Beyond Default\"\nauthor: \"Sheryl Ann Tan Yi-Shi\"\ndate: \"2025-02-15\"\ndate-modified: \"last-modified\"\nexecute: \n  echo: true\n  eval: true\n  warning: false\n  freeze: true\n---\n\n\n\n# 1.0 Introduction\n\n## 1.1 Background\n\nThe maritime sector is one of the most critical components of global trade, contributing significantly to economic growth and sustainability. Understanding ship performance through financial and operational metrics provides valuable insights into profitability and efficiency of shipping operations in the Gulf of Guinea.\n\n## 1.2 The Task\n\nThis exercise involves assuming the role of a graphical editor at an international media company that regularly publishes content on digital platforms. The company plans to release articles focused on one of the following themes:\n\n-   Heart Attack in Japan\n\n-   Ship Performance in the Gulf of Guinea\n\nThe selected theme for this task is ***Ship Performance in the Gulf of Guinea*** and the objective is to prepare data visualisation for the article.\n\n## 1.3 About the Dataset\n\nThe dataset used in this exercise is sourced from Kaggle. It can be accessed via this [link](https://www.kaggle.com/datasets/jeleeladekunlefijabi/ship-performance-clustering-dataset/data).\n\nThis dataset contains information on key operational metrics and attributes of various ship types in the Gulf of Guinea. The dataset includes numerical (e.g. `speed_over_ground_knots`, `revenue_per_voyage_usd`) and categorical variables (e.g. `ship_type`, `maintenance_status`) relevant to ship performance evaluation.\n\n# 2.0 Data Preparation\n\n## 2.1 Loading R Packages\n\nThe following R packages were used:\n\n| R Package   | Description                                                |\n|-------------|------------------------------------------------------------|\n| `dplyr`     | For data manipulation, data wrangling and summarisation.   |\n| `tidyverse` |                                                            |\n| `lubridate` | For working with dates and times.                          |\n| `scales`    | For formatting numeric data                                |\n| `plotly`    | For creating interactive plots.                            |\n| `ggthemes`  | For providing additional themes for ggplot2.               |\n| `ggridges`  | For creating ridgeline plots.                              |\n| `ggplot2`   | For creating plots.                                        |\n| `ggdist`    | For visualising probability distributions in ggplot2.      |\n| `patchwork` | For combining multiple ggplot2 plots into a single layout. |\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(plotly, ggthemes, ggridges,\n               patchwork, ggplot2, tidyverse, dplyr, lubridate, ggdist) \n```\n:::\n\n\n\n## 2.2 Importing the Data\n\nThe dataset was imported into R using the `read_csv` function from the `readr` package, which is part of the `tidyverse` suite.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nship_data <- read_csv(\"data/ship_performance_dataset.csv\")\n```\n:::\n\n\n\n## 2.3 Understanding the Data and Data Wrangling\n\nTo gain an initial understanding of the dataset, the following code chunk utilises the `glimpse` function from the `dplyr` package. This function provides a quick overview of the dataset's structure by displaying the first few entries of each column along with their data types.\n\n::: panel-tabset\n#### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(ship_data)\n```\n:::\n\n\n\n#### Results\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,736\nColumns: 18\n$ Date                    <date> 2023-06-04, 2023-06-11, 2023-06-18, 2023-06-2…\n$ Ship_Type               <chr> \"Container Ship\", \"Fish Carrier\", \"Container S…\n$ Route_Type              <chr> \"None\", \"Short-haul\", \"Long-haul\", \"Transocean…\n$ Engine_Type             <chr> \"Heavy Fuel Oil (HFO)\", \"Steam Turbine\", \"Dies…\n$ Maintenance_Status      <chr> \"Critical\", \"Good\", \"Fair\", \"Fair\", \"Fair\", \"F…\n$ Speed_Over_Ground_knots <dbl> 12.59756, 10.38758, 20.74975, 21.05510, 13.742…\n$ Engine_Power_kW         <dbl> 2062.9840, 1796.0574, 1648.5567, 915.2618, 108…\n$ Distance_Traveled_nm    <dbl> 1030.9436, 1060.4864, 658.8741, 1126.8225, 144…\n$ Draft_meters            <dbl> 14.132284, 14.653083, 7.199261, 11.789063, 9.7…\n$ Weather_Condition       <chr> \"Moderate\", \"Rough\", \"Moderate\", \"Moderate\", \"…\n$ Cargo_Weight_tons       <dbl> 1959.0179, 162.3947, 178.0409, 1737.3853, 260.…\n$ Operational_Cost_USD    <dbl> 483832.35, 483388.00, 448543.40, 261349.61, 28…\n$ Revenue_per_Voyage_USD  <dbl> 292183.27, 883765.79, 394018.75, 87551.38, 676…\n$ Turnaround_Time_hours   <dbl> 25.86708, 63.24820, 49.41815, 22.40911, 64.158…\n$ Efficiency_nm_per_kWh   <dbl> 1.4551789, 0.2903614, 0.4995945, 0.7029057, 1.…\n$ Seasonal_Impact_Score   <dbl> 1.4156533, 0.8856478, 1.4058132, 1.3707043, 0.…\n$ Weekly_Voyage_Count     <dbl> 1, 6, 9, 1, 8, 7, 3, 6, 8, 2, 9, 4, 3, 7, 7, 3…\n$ Average_Load_Percentage <dbl> 93.76925, 93.89537, 96.21824, 66.19370, 80.008…\n```\n\n\n:::\n:::\n\n\n:::\n\nBased on the output generated, the dataset consists of 2,736 rows and 18 columns. Based on the **Date** column, it seems that each row represents weekly data of shipping routes.\n\n### 2.3.1 Duplicate and Missing Value Checks\n\n**Duplicate Data Check**\n\nAs duplicates can skew analysis results, identifying and removing them is crucial for subsequent analysis. Thus, a check for duplicate records was done using the `dplyr` package as shown in the code chunk below:\n\n::: panel-tabset\n#### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduplicate_count <- sum(duplicated(ship_data))\ncat(\"Number of duplicate rows:\", duplicate_count, \"\\n\")\n\nif (duplicate_count > 0) {\n  duplicate_rows <- ship_data[duplicated(ship_data), ]\n  print(duplicate_rows)\n} else {\n  cat(\"No duplicate rows found.\\n\")\n}\n```\n:::\n\n\n\n#### Results\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of duplicate rows: 0 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNo duplicate rows found.\n```\n\n\n:::\n:::\n\n\n:::\n\nBased on the output, there are no duplicate records in the dataset.\n\n**Missing Value Check**\n\nMissing values in a dataset can introduce bias and affect the accuracy of subsequent analysis, potentially leading to misleading results. The following code chunk counts the number of missing values (`NA)` in the dataset:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_value_count <- sum(rowSums(is.na(ship_data)) > 0)\ncat(\"Number of rows with missing values:\", missing_value_count, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of rows with missing values: 0 \n```\n\n\n:::\n:::\n\n\n\nAlthough the output indicates that there are no missing values (`NA`) in the dataset, a further assessment of categorical columns is required to check for unrecorded data. The following code chunk generates the unique values for each categorical column in the dataset:\n\n::: panel-tabset\n#### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncategorical_columns <- names(ship_data)[sapply(ship_data, is.character)]\n\nfor (col in categorical_columns) {\n  cat(\"\\nUnique values in\", col, \":\\n\")\n  print(unique(ship_data[[col]]))\n}\n```\n:::\n\n\n\n#### Results\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nUnique values in Ship_Type :\n[1] \"Container Ship\" \"Fish Carrier\"   \"Bulk Carrier\"   \"None\"          \n[5] \"Tanker\"        \n\nUnique values in Route_Type :\n[1] \"None\"         \"Short-haul\"   \"Long-haul\"    \"Transoceanic\" \"Coastal\"     \n\nUnique values in Engine_Type :\n[1] \"Heavy Fuel Oil (HFO)\" \"Steam Turbine\"        \"Diesel\"              \n[4] \"None\"                \n\nUnique values in Maintenance_Status :\n[1] \"Critical\" \"Good\"     \"Fair\"     \"None\"    \n\nUnique values in Weather_Condition :\n[1] \"Moderate\" \"Rough\"    \"Calm\"     \"None\"    \n```\n\n\n:::\n:::\n\n\n:::\n\nFrom the results, it was observed that some of the columns containing categorical data contained the value ***None***, which may indicate missing or unrecorded data rather than an actual category. To quantify this, the following code counts the occurrences of ***None*** values in the affected categorical columns:\n\n::: panel-tabset\n#### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncategorical_columns <- names(ship_data)[sapply(ship_data, is.character)]\n\nmissing_categorical_counts <- data.frame(Column = categorical_columns, \n                                         Missing_Count = sapply(ship_data[categorical_columns], function(x) sum(is.na(x) | x == \"None\")))\n```\n:::\n\n\n\n#### Results\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                               Column Missing_Count\nShip_Type                   Ship_Type           136\nRoute_Type                 Route_Type           136\nEngine_Type               Engine_Type           136\nMaintenance_Status Maintenance_Status           136\nWeather_Condition   Weather_Condition           136\n```\n\n\n:::\n:::\n\n\n:::\n\nBased on the results obtained above, each affected column contains 136 ***None*** values, representing approximately 5% of the total observations in the dataset. Since the percentage of missing values is relatively low, records containing ***None*** will be excluded from subsequent analysis.\n\n### 2.3.2 Creating New Variables\n\nThe dataset covers the following time period: 4 June 2023 to 30 June 2024. To facilitate time-based analysis, the dates have been grouped into a new variable called ***Month***, which will represent the month of each record in a `\"MM-YYYY\"` format.\n\nThe following code was used to generate these variables:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nship_data$Month <- format(ship_data$Date, \"%Y-%m\")  \n\nhead(ship_data$Month)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2023-06\" \"2023-06\" \"2023-06\" \"2023-06\" \"2023-07\" \"2023-07\"\n```\n\n\n:::\n:::\n\n\n\n**Profit (USD)**\n\nProfit is a key financial metric that reflects the overall economic performance of a ship's operation. To incorporate profit into the dataset, a new variable was created based on the difference between `Revenue_per_Voyage_USD` and `Operational_Cost_USD`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nship_data$Profit_USD <- ship_data$Revenue_per_Voyage_USD - ship_data$Operational_Cost_USD\n\nsummary(ship_data$Profit_USD)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n-444584   40885  262716  266219  492216  977168 \n```\n\n\n:::\n:::\n\n\n\nBased on the summary statistics of the newly created `Profit_USD`, we can observe that some of the ships are loss-making, as shown by the **minimum** value.\n\n### 2.3.3 Data Type Conversion\n\nThe data table below shows the current data type of each of the 19 columns, along with the proposed data type for conversion. To improve data handling and ensure accurate analysis, the proposed data type for each column should align with the nature of the data.\n\n| Variable                | Current Data Type | Proposed Data Type |\n|-------------------------|-------------------|--------------------|\n| Date                    | Date              | Date               |\n| Ship_Type               | Character         | Factor             |\n| Route_Type              | Character         | Factor             |\n| Engine_Type             | Character         | Factor             |\n| Maintenance_Status      | Character         | Ordered Factor     |\n| Speed_Over_Ground_knots | Double            | Double             |\n| Engine_Power_kW         | Double            | Double             |\n| Distance_Traveled_nm    | Double            | Double             |\n| Draft_meters            | Double            | Double             |\n| Weather_Condition       | Character         | Ordered Factor     |\n| Cargo_Weight_tons       | Double            | Double             |\n| Operational_Cost_USD    | Double            | Double             |\n| Revenue_per_Voyage_USD  | Double            | Double             |\n| Turnaround_Time_hours   | Double            | Double             |\n| Efficiency_nm_per_kWh   | Double            | Double             |\n| Seasonal_Impact_Score   | Double            | Double             |\n| Weekly_Voyage_Count     | Double            | Integer            |\n| Average_Load_Percentage | Double            | Double             |\n| Month                   | Character         | Date               |\n| Profit_USD              | Double            | Double             |\n\nThe following code chunk is used to implement the proposed data type conversions:\n\n::: panel-tabset\n#### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nship_data$Ship_Type <- as.factor(ship_data$Ship_Type)\nship_data$Route_Type <- as.factor(ship_data$Route_Type)\nship_data$Engine_Type <- as.factor(ship_data$Engine_Type)\n\nship_data$Maintenance_Status <- factor(ship_data$Maintenance_Status, \n                                       levels = c(\"Critical\", \"Fair\", \"Good\",\"None\"), \n                                       ordered = TRUE)\n\nship_data$Weather_Condition <- factor(ship_data$Weather_Condition, \n                                      levels = c(\"Calm\", \"Moderate\", \"Rough\", \"Severe\",\"None\"), \n                                      ordered = TRUE)\n\nship_data$Month <- as.Date(paste0(ship_data$Month, \"-01\"), format=\"%Y-%m-%d\")\n\nship_data$Weekly_Voyage_Count <- as.integer(ship_data$Weekly_Voyage_Count)\n```\n:::\n\n\n\n#### Results\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,736\nColumns: 20\n$ Date                    <date> 2023-06-04, 2023-06-11, 2023-06-18, 2023-06-2…\n$ Ship_Type               <fct> Container Ship, Fish Carrier, Container Ship, …\n$ Route_Type              <fct> None, Short-haul, Long-haul, Transoceanic, Tra…\n$ Engine_Type             <fct> Heavy Fuel Oil (HFO), Steam Turbine, Diesel, S…\n$ Maintenance_Status      <ord> Critical, Good, Fair, Fair, Fair, Fair, Critic…\n$ Speed_Over_Ground_knots <dbl> 12.59756, 10.38758, 20.74975, 21.05510, 13.742…\n$ Engine_Power_kW         <dbl> 2062.9840, 1796.0574, 1648.5567, 915.2618, 108…\n$ Distance_Traveled_nm    <dbl> 1030.9436, 1060.4864, 658.8741, 1126.8225, 144…\n$ Draft_meters            <dbl> 14.132284, 14.653083, 7.199261, 11.789063, 9.7…\n$ Weather_Condition       <ord> Moderate, Rough, Moderate, Moderate, Moderate,…\n$ Cargo_Weight_tons       <dbl> 1959.0179, 162.3947, 178.0409, 1737.3853, 260.…\n$ Operational_Cost_USD    <dbl> 483832.35, 483388.00, 448543.40, 261349.61, 28…\n$ Revenue_per_Voyage_USD  <dbl> 292183.27, 883765.79, 394018.75, 87551.38, 676…\n$ Turnaround_Time_hours   <dbl> 25.86708, 63.24820, 49.41815, 22.40911, 64.158…\n$ Efficiency_nm_per_kWh   <dbl> 1.4551789, 0.2903614, 0.4995945, 0.7029057, 1.…\n$ Seasonal_Impact_Score   <dbl> 1.4156533, 0.8856478, 1.4058132, 1.3707043, 0.…\n$ Weekly_Voyage_Count     <int> 1, 6, 9, 1, 8, 7, 3, 6, 8, 2, 9, 4, 3, 7, 7, 3…\n$ Average_Load_Percentage <dbl> 93.76925, 93.89537, 96.21824, 66.19370, 80.008…\n$ Month                   <date> 2023-06-01, 2023-06-01, 2023-06-01, 2023-06-0…\n$ Profit_USD              <dbl> -191649.081, 400377.787, -54524.657, -173798.2…\n```\n\n\n:::\n:::\n\n\n:::\n\n# 3.0 Data Visualisation\n\n## 3.1 Financial Metrics\n\n### 3.1.1 Overview of Revenue, Cost and Cargo Weight Trending by Month\n\nThis section provides a time-series analysis of revenue, cost, and cargo weight trends across the observed period to identify key patterns and insights.\n\nThe code chunk below plots a combination of bar and line charts. Cargo weight is represented by a bar chart while revenue and operational costs are illustrated as line plots.\n\n::: panel-tabset\n#### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01b_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n#### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly_summary <- ship_data %>%\n  group_by(Month) %>%\n  summarise(\n    Total_Revenue = sum(Revenue_per_Voyage_USD, na.rm = TRUE),\n    Total_Cost = sum(Operational_Cost_USD, na.rm = TRUE),\n    Total_Cargo_Weight = sum(Cargo_Weight_tons, na.rm = TRUE)\n  )\n\nmonthly_summary$Month <- as.Date(paste0(monthly_summary$Month, \"-01\"), format=\"%Y-%m-%d\")\n\nmax_revenue <- max(monthly_summary$Total_Revenue/1e6, na.rm = TRUE)\nmax_cargo <- max(monthly_summary$Total_Cargo_Weight/1e6, na.rm = TRUE)\nscaling_factor <- max_revenue / max_cargo  \n\n\nggplot(monthly_summary, aes(x = Month)) +\n  geom_col(aes(y = Total_Cargo_Weight/1e6*scaling_factor, fill = \"Cargo Weight (Million Tons)\"), alpha = 0.6) + \n  geom_line(aes(y = Total_Revenue/1e6, color = \"Revenue (in USD Million)\"), size = 1) + \n  geom_line(aes(y = Total_Cost/1e6, color = \"Operational Cost (in USD Million)\"), size = 1, linetype = \"dashed\") +\n  scale_y_continuous(\n    name = \"Revenue & Cost (in USD Million)\", \n    labels = scales::dollar_format(suffix = \"M\", prefix = \"\"),\n    sec.axis = sec_axis(~ ./scaling_factor, name = \"Cargo Weight (Million Tons)\")  \n  ) +\n  scale_x_date(\n    date_labels = \"%b %Y\",\n    breaks = seq(min(monthly_summary$Month), max(monthly_summary$Month), by = \"1 month\")\n  ) +\n  labs(\n    title = \"Revenue, Cost, and Cargo Weight by Month\",\n    x = \"Month\",\n    fill = \"Metric\",\n    color = \"Metric\"\n  ) +\n  scale_fill_manual(values = c(\"Cargo Weight (Million Tons)\" = \"lightblue\")) +  \n  scale_color_manual(values = c(\n    \"Revenue (in USD Million)\" = \"black\",\n    \"Operational Cost (in USD Million)\" = \"darkred\"\n  )) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5, size = 14, face = \"bold\"),\n    axis.text.x = element_text(angle = 45, hjust = 1),\n    legend.position = \"top\"\n  )\n```\n:::\n\n\n:::\n\n::: {.callout-note icon=\"false\"}\n#### Insights\n\n1.  Revenue consistently exceeds operational costs across all months, indicating that operations remain profitable throughout the observed period.\n\n2.  Revenue, operational costs and cargo weight exhibit similar trends. In months where cargo weight increases, both revenue and costs rise accordingly, and vice versa. This suggests a positive correlation between all three variables.\n\n3.  There is no clear growth trend over the observed period, as fluctuations in cargo weight, revenue, and costs occur over time. Further research could be undertaken to understand if these variations could be attributed to seasonal demand shifts or external factors such as global economic conditions affecting shipping volumes.\n:::\n\n### 3.1.2 Profitability by Ship Types\n\nIn this section, we will analyze the profitability across different ship types to gain insights into their profitability trends and variability.\n\nThe code chunk below generates three plots to explore the profitability of different ship types. Firstly, the bar chart presents the total profit across ship types, ranking them from highest to lowest profit. Next, the boxplot provides insight into the distribution of profit, highlighting the variability and median values across ship types. Lastly, the ridgeline plot illustrates the profit distribution across ship types. The `patchwork` function is then used to combine these plots together.\n\n::: panel-tabset\n#### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01b_files/figure-html/unnamed-chunk-18-1.png){width=1152}\n:::\n:::\n\n\n\n#### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfiltered_ship_data1 <- ship_data %>% filter(Ship_Type != \"None\")\n\n\n\nmedians <- filtered_ship_data1 %>%\n  group_by(Ship_Type) %>%\n  summarize(Median_Profit = median(Profit_USD/1e6, na.rm = TRUE))\n\nfiltered_ship_data1 <- filtered_ship_data1 %>%\n  left_join(medians, by = \"Ship_Type\")\n\n\n\np1 <- ggplot(data=filtered_ship_data1, aes(y=Profit_USD/1e6, x=reorder(Ship_Type, Median_Profit), fill = Ship_Type)) +\n  geom_boxplot(notch=TRUE, show.legend = FALSE) +\n  geom_text(data = medians,\n            aes(label = sprintf(\"%.2fM\", Median_Profit), y = Median_Profit),\n            nudge_y = 0.1, size = 3.5) +\n  scale_y_continuous(labels = scales::dollar_format(suffix = \"M\", prefix = \"$\"), limits = c(-1.0,1.5)) + \n  labs(\n    title = \"Profit Distribution by Ship Type\",\n    x = NULL,  \n    y = \"Profit (in USD Million)\"\n  ) +\n  coord_flip() +\n  theme_classic() +\n  theme(\n    plot.title = element_text(hjust = 0.5, size = 14, face = \"bold\"),\n    axis.title.x = element_blank(),\n    axis.text.y = element_text(size = 12)\n  )\n\n\n\np2 <- ggplot(data = filtered_ship_data1, aes(x = Profit_USD / 1e6, y = reorder(Ship_Type, Median_Profit), fill = Ship_Type)) +\n  geom_density_ridges(aes(group = Ship_Type, fill = Ship_Type), alpha = 0.8, show.legend = FALSE) +\n  scale_x_continuous(labels = scales::dollar_format(suffix = \"M\", prefix = \"$\"), limits = c(-1.0,1.5)) +\n  labs(\n    x = \"Profit (in USD Million)\",\n    y = NULL\n  ) +\n  theme_classic() + \n  theme(\n    axis.text.y = element_text(size = 12)\n  )\n\n\n\nprofit_summary <- ship_data %>%\n  filter(Ship_Type != \"None\") %>%\n  group_by(Ship_Type) %>%\n  summarise(Total_Profit = sum(Profit_USD, na.rm = TRUE)) %>%\n  arrange(desc(Total_Profit)) \n\n\n\np3 <- ggplot(profit_summary, aes(x = reorder(Ship_Type, Total_Profit), y = Total_Profit, fill = Ship_Type)) +\n  geom_col(show.legend = FALSE) + \n  geom_text(aes(label = sprintf(\"%.2fM\", Total_Profit / 1e6)), \n            hjust = 1.5, size = 3.5) +\n  coord_flip() + \n  scale_y_continuous(labels = scales::dollar_format(prefix = \"$\", suffix = \"M\", scale = 1e-6)) +\n  labs(\n    title = \"Total Profit by Ship Type\",\n    x = NULL, \n    y = \"Profit (in USD Million)\"\n  ) +\n  theme_classic() +\n  theme(\n    plot.title = element_text(hjust = 0.5, size = 14, face = \"bold\"),\n    plot.margin = margin(10, 40, 10, 10),\n    axis.text.y = element_text(size = 12))\n\n\ncombined_plot <- (p3 | (p1 / p2)) + \n  plot_layout(widths = c(1, 2.5)) +\n  plot_annotation(\n    title = \"Profitability by Ship Types\",\n    theme = theme(\n      plot.title = element_text(hjust = 0.5, size = 18, face = \"bold\")\n    )\n  )\n\ncombined_plot\n```\n:::\n\n\n:::\n\n::: {.callout-note icon=\"false\"}\n#### Insights\n\n1.  **Fish Carriers** generated the highest total profit while **Tankers** generated the lowest. This pattern is also reflected in median profits, with **Tankers** having the lowest median profit at US\\$0.23M. Furthermore, the notch of the boxplot for **Tankers** does not overlap with the notches of the other ship types, suggesting that the median profit for **Tankers** is significantly lower.\n\n2.  Although the median profits for **Fish Carriers, Container Ships** and **Bulk Carriers** are similar (indicated by their overlapping boxplot notches), their profit distributions differ:\n\n    \\(a\\) **Bulk Carriers** display a bimodal distribution, indicating two distinct groups - some Bulk Carriers are highly profitable while others operate at lower margins.\n\n    \\(b\\) **Fish Carriers** and **Container Ships** exhibit unimodal distributions. However, **Container Ships** appear to have a higher profit variability as indicated by the greater range and IQR in the boxplot.\n:::\n\n### 3.1.3 Sales and Profitability by Route Types\n\nIn this section, we will analyse the sales and profitability trends by route types on a quarterly basis. Since June 2023 represents an incomplete quarter, it has been excluded to ensure consistency in our quarterly comparisons.\n\nThe analysis assumes that the fiscal year starts in July. Hence, we will define the quarters as follows:\n\n-   **Q1** = July 2023 - September 2023\n\n-   **Q2** = October 2023 - December 2023\n\n-   **Q3 =** January 2024 - March 2024\n\n-   **Q4** = April 2024 - June 2024\n\nEach chart is divided into four quadrants to help interpret the relationship between sales and profit:\n\n-   **High Profit, High Sales** (Top Right)\n\n-   **High Profit, Low Sales**(Top Left)\n\n-   **Low Profit, High Sales** (Bottom Right): This could indicate potential issues with cost management or pricing.\n\n-   **Low Profit, Low Sales** (Bottom Left): Potentially requires attention.\n\nThe code chunk below generates a facet gird consisting of bubble charts, with each panel representing a quarterly breakdown of sales and profitability by route type. The bubble size corresponds to the profit margin percentage.\n\nThe code chunk also generates an interactive plot using `plotly`. It allows users to hover over each data point to view details such as route type, total sales, total profit and profit margin.\n\n::: panel-tabset\n#### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-8383d71b6d3fb6786ebc\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-8383d71b6d3fb6786ebc\">{\"x\":{\"data\":[{\"x\":[0.33333333333333331],\"y\":[0.66666666666666663],\"text\":\"Route Type: Coastal <br>Sales: $74.05M <br>Profit: $38.21M <br>Profit Margin: 51.6%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(248,118,109,1)\",\"opacity\":0.69999999999999996,\"size\":43.929061332218616,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"Coastal\",\"legendgroup\":\"Coastal\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.66666666666666663],\"y\":[0.66666666666666663],\"text\":\"Route Type: Coastal <br>Sales: $85.85M <br>Profit: $40.86M <br>Profit Margin: 47.6%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(248,118,109,1)\",\"opacity\":0.69999999999999996,\"size\":25.103453710446519,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"Coastal\",\"legendgroup\":\"Coastal\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.33333333333333331],\"y\":[1],\"text\":\"Route Type: Coastal <br>Sales: $78.05M <br>Profit: $41.94M <br>Profit Margin: 53.7%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(248,118,109,1)\",\"opacity\":0.69999999999999996,\"size\":50.394035314683784,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"Coastal\",\"legendgroup\":\"Coastal\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.33333333333333331],\"y\":[0.66666666666666663],\"text\":\"Route Type: Coastal <br>Sales: $74.88M <br>Profit: $41.10M <br>Profit Margin: 54.9%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(248,118,109,1)\",\"opacity\":0.69999999999999996,\"size\":53.490393110871111,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"Coastal\",\"legendgroup\":\"Coastal\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1],\"y\":[1],\"text\":\"Route Type: Long-haul <br>Sales: $88.00M <br>Profit: $49.44M <br>Profit Margin: 56.2%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(124,174,0,1)\",\"opacity\":0.69999999999999996,\"size\":56.692913385826778,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(124,174,0,1)\"}},\"hoveron\":\"points\",\"name\":\"Long-haul\",\"legendgroup\":\"Long-haul\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.33333333333333331],\"y\":[0.33333333333333331],\"text\":\"Route Type: Long-haul <br>Sales: $83.46M <br>Profit: $39.00M <br>Profit Margin: 46.7%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(124,174,0,1)\",\"opacity\":0.69999999999999996,\"size\":11.338582677165356,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(124,174,0,1)\"}},\"hoveron\":\"points\",\"name\":\"Long-haul\",\"legendgroup\":\"Long-haul\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.66666666666666663],\"y\":[0.66666666666666663],\"text\":\"Route Type: Long-haul <br>Sales: $83.60M <br>Profit: $41.63M <br>Profit Margin: 49.8%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(124,174,0,1)\",\"opacity\":0.69999999999999996,\"size\":37.196184260961317,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(124,174,0,1)\"}},\"hoveron\":\"points\",\"name\":\"Long-haul\",\"legendgroup\":\"Long-haul\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1],\"y\":[1],\"text\":\"Route Type: Long-haul <br>Sales: $84.84M <br>Profit: $44.99M <br>Profit Margin: 53.0%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(124,174,0,1)\",\"opacity\":0.69999999999999996,\"size\":48.388095659118342,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(124,174,0,1)\"}},\"hoveron\":\"points\",\"name\":\"Long-haul\",\"legendgroup\":\"Long-haul\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.66666666666666663],\"y\":[0.33333333333333331],\"text\":\"Route Type: Short-haul <br>Sales: $76.55M <br>Profit: $37.12M <br>Profit Margin: 48.5%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,191,196,1)\",\"opacity\":0.69999999999999996,\"size\":30.931412031570801,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"Short-haul\",\"legendgroup\":\"Short-haul\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1],\"y\":[1],\"text\":\"Route Type: Short-haul <br>Sales: $88.46M <br>Profit: $45.26M <br>Profit Margin: 51.2%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,191,196,1)\",\"opacity\":0.69999999999999996,\"size\":42.406394400458069,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"Short-haul\",\"legendgroup\":\"Short-haul\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0],\"y\":[0],\"text\":\"Route Type: Short-haul <br>Sales: $68.63M <br>Profit: $37.17M <br>Profit Margin: 54.2%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,191,196,1)\",\"opacity\":0.69999999999999996,\"size\":51.555530668226901,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"Short-haul\",\"legendgroup\":\"Short-haul\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0],\"y\":[0],\"text\":\"Route Type: Short-haul <br>Sales: $68.50M <br>Profit: $34.51M <br>Profit Margin: 50.4%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,191,196,1)\",\"opacity\":0.69999999999999996,\"size\":39.518465957647564,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"Short-haul\",\"legendgroup\":\"Short-haul\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0],\"y\":[0],\"text\":\"Route Type: Transoceanic <br>Sales: $73.02M <br>Profit: $35.38M <br>Profit Margin: 48.5%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(199,124,255,1)\",\"opacity\":0.69999999999999996,\"size\":30.724782853764772,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(199,124,255,1)\"}},\"hoveron\":\"points\",\"name\":\"Transoceanic\",\"legendgroup\":\"Transoceanic\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0],\"y\":[0],\"text\":\"Route Type: Transoceanic <br>Sales: $72.05M <br>Profit: $36.00M <br>Profit Margin: 50.0%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(199,124,255,1)\",\"opacity\":0.69999999999999996,\"size\":37.910595871347567,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(199,124,255,1)\"}},\"hoveron\":\"points\",\"name\":\"Transoceanic\",\"legendgroup\":\"Transoceanic\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1],\"y\":[0.33333333333333331],\"text\":\"Route Type: Transoceanic <br>Sales: $86.59M <br>Profit: $40.66M <br>Profit Margin: 47.0%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(199,124,255,1)\",\"opacity\":0.69999999999999996,\"size\":18.467708205033105,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(199,124,255,1)\"}},\"hoveron\":\"points\",\"name\":\"Transoceanic\",\"legendgroup\":\"Transoceanic\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.66666666666666663],\"y\":[0.33333333333333331],\"text\":\"Route Type: Transoceanic <br>Sales: $78.27M <br>Profit: $40.41M <br>Profit Margin: 51.6%\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(199,124,255,1)\",\"opacity\":0.69999999999999996,\"size\":43.996422381001175,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(199,124,255,1)\"}},\"hoveron\":\"points\",\"name\":\"Transoceanic\",\"legendgroup\":\"Transoceanic\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[-0.050000000000000003,1.05],\"y\":[0.5,0.5],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.1338582677165354,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[-0.050000000000000003,1.05],\"y\":[0.5,0.5],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.1338582677165354,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[-0.050000000000000003,1.05],\"y\":[0.5,0.5],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.1338582677165354,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[-0.050000000000000003,1.05],\"y\":[0.5,0.5],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.1338582677165354,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.5,0.5],\"y\":[-0.050000000000000003,1.05],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.1338582677165354,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.5,0.5],\"y\":[-0.050000000000000003,1.05],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.1338582677165354,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.5,0.5],\"y\":[-0.050000000000000003,1.05],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.1338582677165354,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.5,0.5],\"y\":[-0.050000000000000003,1.05],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.1338582677165354,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":56.51473640514736,\"r\":7.3059360730593621,\"b\":40.182648401826491,\"l\":48.949771689497723},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"<b> Sales and Profit by Route Types <\\/b>\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":18.596928185969279},\"x\":0.5,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,0.48392857142857143],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.050000000000000003,1.05],\"tickmode\":\"array\",\"ticktext\":[\"0%\",\"25%\",\"50%\",\"75%\",\"100%\"],\"tickvals\":[0,0.25,0.5,0.75,1],\"categoryorder\":\"array\",\"categoryarray\":[\"0%\",\"25%\",\"50%\",\"75%\",\"100%\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y2\",\"title\":\"\",\"hoverformat\":\".2f\"},\"annotations\":[{\"text\":\"Sales Percentile\",\"x\":0.5,\"y\":0,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"top\",\"annotationType\":\"axis\",\"yshift\":-21.917808219178088},{\"text\":\"Profit Percentile\",\"x\":0,\"y\":0.5,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-90,\"xanchor\":\"right\",\"yanchor\":\"center\",\"annotationType\":\"axis\",\"xshift\":-33.607305936073068},{\"text\":\"Q1\",\"x\":0.24196428571428572,\"y\":1,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Q2\",\"x\":0.75803571428571437,\"y\":1,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Q3\",\"x\":0.24196428571428572,\"y\":0.46836757990867578,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Q4\",\"x\":0.75803571428571437,\"y\":0.46836757990867578,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.68949771689498},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"}],\"yaxis\":{\"domain\":[0.53163242009132416,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.050000000000000003,1.05],\"tickmode\":\"array\",\"ticktext\":[\"0%\",\"25%\",\"50%\",\"75%\",\"100%\"],\"tickvals\":[0,0.25,0.5,0.75,1],\"categoryorder\":\"array\",\"categoryarray\":[\"0%\",\"25%\",\"50%\",\"75%\",\"100%\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":\"\",\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.48392857142857143,\"y0\":0.53163242009132416,\"y1\":1},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.48392857142857143,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":1,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.51607142857142863,\"x1\":1,\"y0\":0.53163242009132416,\"y1\":1},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.51607142857142863,\"x1\":1,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":1,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.48392857142857143,\"y0\":0,\"y1\":0.46836757990867578},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.48392857142857143,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":0.46836757990867578,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.51607142857142863,\"x1\":1,\"y0\":0,\"y1\":0.46836757990867578},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.51607142857142863,\"x1\":1,\"y0\":0,\"y1\":23.37899543378996,\"yanchor\":0.46836757990867578,\"ysizemode\":\"pixel\"}],\"xaxis2\":{\"type\":\"linear\",\"autorange\":false,\"range\":[-0.050000000000000003,1.05],\"tickmode\":\"array\",\"ticktext\":[\"0%\",\"25%\",\"50%\",\"75%\",\"100%\"],\"tickvals\":[0,0.25,0.5,0.75,1],\"categoryorder\":\"array\",\"categoryarray\":[\"0%\",\"25%\",\"50%\",\"75%\",\"100%\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0.51607142857142863,1],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y2\",\"title\":\"\",\"hoverformat\":\".2f\"},\"yaxis2\":{\"type\":\"linear\",\"autorange\":false,\"range\":[-0.050000000000000003,1.05],\"tickmode\":\"array\",\"ticktext\":[\"0%\",\"25%\",\"50%\",\"75%\",\"100%\"],\"tickvals\":[0,0.25,0.5,0.75,1],\"categoryorder\":\"array\",\"categoryarray\":[\"0%\",\"25%\",\"50%\",\"75%\",\"100%\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0,0.46836757990867578],\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":\"\",\"hoverformat\":\".2f\"},\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"Profit Margin (%)<br />Route Type\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"189c39be12e5\":{\"x\":{},\"y\":{},\"size\":{},\"colour\":{},\"text\":{},\"type\":\"scatter\"},\"189c42577bfe\":{\"yintercept\":{}},\"189c4d031e35\":{\"xintercept\":{}}},\"cur_data\":\"189c39be12e5\",\"visdat\":{\"189c39be12e5\":[\"function (y) \",\"x\"],\"189c42577bfe\":[\"function (y) \",\"x\"],\"189c4d031e35\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n#### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroute_summary <- ship_data %>%\n  filter(Route_Type != \"None\") %>%\n  filter(!(year(Month) == 2023 & month(Month) == 6)) %>%\n  mutate(Quarter = case_when(\n    month(Month) %in% 7:9  ~ \"Q1\",  \n    month(Month) %in% 10:12 ~ \"Q2\", \n    month(Month) %in% 1:3  ~ \"Q3\",  \n    month(Month) %in% 4:6  ~ \"Q4\"   \n  )) %>%\n  filter(!is.na(Quarter)) %>% \n  group_by(Quarter, Route_Type) %>%\n  summarise(\n    Total_Sales = sum(Revenue_per_Voyage_USD, na.rm = TRUE),\n    Total_Profit = sum(Profit_USD, na.rm = TRUE),\n    Profit_Margin = ifelse(Total_Sales > 0, (Total_Profit / Total_Sales) * 100, NA)  \n  ) %>%\n  mutate(\n    Sales_Percentile = percent_rank(Total_Sales), \n    Profit_Percentile = percent_rank(Total_Profit)\n  )\n\np <- ggplot(route_summary, aes(x = Sales_Percentile, y = Profit_Percentile, \n                               size = Profit_Margin, color = Route_Type,\n                               text = paste(\"Route Type:\", Route_Type,\n                                            \"<br>Sales:\", scales::dollar(Total_Sales / 1e6, suffix = \"M\"),\n                                            \"<br>Profit:\", scales::dollar(Total_Profit / 1e6, suffix = \"M\"),\n                                            \"<br>Profit Margin:\", sprintf(\"%.1f%%\", Profit_Margin)))) +\n  geom_point(alpha = 0.7) + \n  geom_hline(yintercept = 0.5, linetype = \"dashed\", color = \"black\", size = 0.3) +\n  geom_vline(xintercept = 0.5, linetype = \"dashed\", color = \"black\", size = 0.3) +  \n  scale_size(range = c(3, 15), name = \"Profit Margin (%)\", guide = guide_legend(title = \"Profit Margin (%)\")) +\n  scale_x_continuous(labels = scales::percent_format()) +\n  scale_y_continuous(labels = scales::percent_format()) +\n  labs(\n    title = \"Sales and Profit by Route Types\",\n    x = \"Sales Percentile\",\n    y = \"Profit Percentile\",\n    color = \"Route Type\",\n    size = \"Profit Margin (%)\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5, size = 14, face = \"bold\"),\n    legend.position = \"right\",\n    panel.spacing = unit(1.5, \"lines\")  \n  ) +\n  facet_wrap(~ Quarter, ncol = 2)\n\n\np_interactive <- ggplotly(p, tooltip = \"text\")\n\np_interactive\n```\n:::\n\n\n:::\n\n::: {.callout-note icon=\"false\"}\n#### Insights\n\n1.  **Long-Haul Routes** predominantly occupy the top-right quadrant, indicating strong performance in both sales and profit across most quarters. However, in Q2, they fall into the low sales, low profit quadrant, suggesting weaker performance during this period. They also have the lowest profit margin in Q2.\n\n2.  **Coastal Routes** consistently rank above the 50th percentile in profitability across all quarters, reinforcing their high-margin nature. However, sales performance fluctuates, with sales falling below the 50th percentile in three out of four quarters.\n\n3.  **Transoceanic Routes** consistently rank below the 50th percentile in profitability across all quarters. Their sales performance is weakest in Q1 and Q2 but show improvement in Q3 and Q4. These routes exhibit the lowest profitability and sales in Q1 and Q2.\n\n4.  **Short-Haul Routes** exhibit the lowest profitability and sales in Q3 and Q4, replacing Transoceanic Routes as the weakest performing category in those quarters.\n:::\n\n## 3.2 Operational Metrics\n\n### 3.2.1 Average Load Percentage by Ship Types Across Route Types\n\nThis section examines the distribution of average load percentage across different ship types and routes types. By visualising the density distribution of load percentage, this section aims to understand how efficiently different ship types utilise their cargo capacity on various routes.\n\nThe code chunk below plots the density distributions of average load percentage for different ship types across route types using `geom_density`. A reference line representing the median load percentage for each route type is added to provide a benchmark for further interpretation.\n\n::: panel-tabset\n#### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01b_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n#### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| fig-width: 12\n#| fig-height: 8\n\nfiltered_data2 <- ship_data %>%\n  filter(Ship_Type != \"None\", Route_Type != \"None\")\n\nmedian_values <- filtered_data2 %>%\n  group_by(Route_Type) %>%\n  summarise(Median_Load = median(Average_Load_Percentage, na.rm = TRUE), .groups = \"drop\")\n\n\nggplot(filtered_data2, aes(x = Average_Load_Percentage, color = Ship_Type)) +\n  geom_density(alpha = 0.7) +  \n  geom_vline(data = median_values, aes(xintercept = Median_Load), \n             linetype = \"dashed\", size = 0.5, color = \"black\") +\n  geom_text(data = median_values, \n            aes(x = Median_Load, y = 0, \n                label = sprintf(\"Median: %.1f%%\", Median_Load)), \n            hjust = 1.1, vjust = -1.5, size = 2.5, color = \"black\") + \n  labs(\n    title = \"Average Load Percentage by Ship Types Across Routes\",\n    x = \"Average Load Percentage (%)\",\n    y = \"Density\",\n    color = \"Ship Type\"\n  ) +\n  facet_wrap(~ Route_Type, ncol = 2) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5, size = 14, face = \"bold\")\n  )\n```\n:::\n\n\n:::\n\n::: {.callout-note icon=\"false\"}\n#### Insights\n\n1.  **Coastal Routes**: **Tankers** exhibit a left-skewed distribution, with a distinct peak in the 90% - 95% range, indicating a higher frequency of tankers operating at high load capacities. In contrast, other ship types demonstrate a more uniform distribution.\n\n2.  **Long-Haul Routes**: All ship types exhibit a relatively uniform distribution.\n\n3.  **Short-Haul Routes**: **Container Ships** exhibit a right-skewed distribution, with a peak in the 60% - 65% range, indicating a higher frequency of container ships operating with lower load capacities. In contrast, both **Bulk Carriers** and **Tankers** exhibit a left-skew distribution, suggesting a tendency toward higher load capacities.\n\n4.  **Transoceanic Routes**: Most ship types exhibit a relatively uniform distribution, except for **Bulk Carriers**, which display a distinct peak in the 80% - 85% range. This indicates a higher concentration of bulk carriers operating within this load percentage.\n:::\n\n### 3.2.2 Number of Voyages and Cargo Weight by Route Types\n\nThis section analyses the number of voyages and cargo weight across different route types over the observed period. By visualising this data, we can identify trends, such as which routes experience higher shipping volumes and whether voyage frequency aligns with cargo weight trends.\n\nThe code chunk below aggregates the total number of voyages and cargo weight (in tons) for each route type by quarter. A bar chart is used to represent the number of voyages, while a line chart overlays the total cargo weight to show the relationship between voyage frequency and cargo volume.\n\n::: panel-tabset\n#### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01b_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n#### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| fig-width: 12\n#| fig-height: 8\n\nlibrary(scales)\n\nfiltered_data3 <- ship_data %>%\n  filter(Route_Type != \"None\") %>%\n  filter(!(year(Month) == 2023 & month(Month) == 6)) %>%\n  mutate(\n    Quarter = case_when(\n      month(Month) %in% 7:9  ~ \"Q1\",  \n      month(Month) %in% 10:12 ~ \"Q2\", \n      month(Month) %in% 1:3  ~ \"Q3\",  \n      month(Month) %in% 4:6  ~ \"Q4\"\n    )\n  ) %>%\n  filter(!is.na(Quarter)) \n\nsummary_data <- filtered_data3 %>%\n  group_by(Quarter, Route_Type) %>%\n  summarise(\n    Total_Voyages = sum(Weekly_Voyage_Count, na.rm = TRUE),\n    Total_Cargo_Weight = sum(Cargo_Weight_tons, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\nmax_voyages <- max(summary_data$Total_Voyages, na.rm = TRUE)\nmax_cargo <- max(summary_data$Total_Cargo_Weight, na.rm = TRUE)\nscaling_factor <- max_voyages / max_cargo\n\n\nggplot(summary_data, aes(x = Route_Type)) +\n  \n  geom_col(aes(y = Total_Voyages, fill = Route_Type), position = \"dodge\", alpha = 0.7) +\n  \n  geom_line(aes(y = Total_Cargo_Weight * scaling_factor, group = 1, color = \"Total Cargo Weight (Tons)\"), size = 1.2) +\n  geom_point(aes(y = Total_Cargo_Weight * scaling_factor, color = \"Total Cargo Weight (Tons)\"), size = 2) +\n\n  scale_y_continuous(\n    name = \"Total Number of Voyages\",\n    labels = comma_format(),  \n    sec.axis = sec_axis(~ . / scaling_factor, name = \"Total Cargo Weight (Tons)\", labels = comma_format())\n  ) +\n  \n  scale_color_manual(name = \" \", values = c(\"Total Cargo Weight (Tons)\" = \"black\")) +  \n\n  labs(\n    title = \"Number of Voyages and Cargo Weight (Tons) by Route Type\",\n    x = NULL, \n    fill = \"Route Type\"\n  ) +\n  facet_wrap(~ Quarter, ncol = 2) + \n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = -0.2, size = 14, face = \"bold\"),\n    panel.spacing = unit(1, \"cm\"),\n    axis.text.x = element_blank(),\n    axis.ticks.x = element_blank()\n  )\n```\n:::\n\n\n:::\n\n::: {.callout-note icon=\"false\"}\n#### Insights\n\n1.  **Short-haul Routes** recorded the highest number of voyages and cargo weight in Q2. However, it was followed by a significant decreased in Q3 and Q4, recording the lowest number of voyages and total cargo weight.\n\n2.  **Transoceanic Routes** had the lowest number of voyages and total cargo weight in Q1 and Q2, but saw a significant increase in Q3 and Q4, making them the busiest route type in the second half of the year.\n\n3.  **Long-haul Routes** maintained a relatively stable number of voyages and total cargo weight throughout the observed period.\n\n4.  **Coastal Routes** experienced lower voyage activity in Q1 and Q4, with slightly higher voyage counts in Q2 and Q3.\n\n5.  Cargo weight generally followed the same trend as the number of voyages, with the exception of Q1.\n:::\n\n# 4.0 Key Findings and Observations\n\nThis section summarises the key observation points derived from the data visualisation of ship performance (i.e. financial and operational performance) in the Gulf of Guinea.\n\n## 4.1 Financial Performance\n\nGenerally, shipping operations remained profitable throughout the observed period. Fluctuations in revenue and costs aligned with variations in total cargo weight, suggesting a positive correlation between shipping volume and financial performance.\n\nFish Carriers achieved the highest profitability while Tankers had the lowest profitability. Similarly, Long-haul Routes consistently outperformed other routes in both sales and profit, except in Q2. Transoceanic Routes had the weakest performance in Q1 and Q2 while Short-haul Routes recorded the weakest performance in Q3 and Q4.\n\n## 4.2 Operational Performance\n\nA higher proportion of tankers operate at higher load capacities on Coastal and Short-haul routes. However, a higher proportion of Container Ships operate at lower load capacities on Short-haul Routes.\n\nTotal cargo weight generally followed the same trend as the number of voyages, with Short-haul Routes recording the lowest number of voyages and cargo weight in Q3 and Q4.\n\n# 5.0 Future Work\n\nThe dataset had several limitations:\n\n-    The dataset includes a **Seasonal Impact Score**. However, it was difficult to interpret the scores as it was unclear how this variable was computed.\n\n-   The dataset only covered a limited time frame, i.e. one year. This may not be sufficient to fully capture long-term trends or cyclical market conditions.\n\nWhile the analysis provided key insights into ship performance and operational trends, further research can be performed to improve understanding.\n\nSome future work that could be undertaken include:\n\n-   Extending the analysis beyond the observed period of one year as it may allow for better understanding of seasonal and long-term trends.\n\n-   Analysing the types of cargo transported (e.g. bulk commodities, liquid cargo, containerised goods) on top of cargo weight would provide insights into which type of shipments contribute most to profitability.\n\n# 6.0 References\n\nKam, T. S. (2023). *R for Visual Analytics*. Retrieved from <https://r4va.netlify.app>\n",
    "supporting": [
      "Take-Home_Ex01b_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.4/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}